### ISSUE TITLE
SSL compatibility

### ISSUE THREAD

**Issue by PxSonny** [jhrv/sensu-influxdb-extension#11]
Hi, 

I activated SSL on my InfluxDB instance and now it seems I can't get the extension to connect to it. 
I am using a certificate signed by myself, so I am guessing it may need some kind of acceptation somewhere to able ruby to reach the InfluxAPI. 

I tried to add:

``` ruby
      @http = Net::HTTP::new(@uri.host, @uri.port)
      @http.ssl_version = :TLSv1
      @http.use_ssl = true
      @http.verify_mode = OpenSSL::SSL::VERIFY_PEER
      @http.ca_file = "mycertificate.pem"
```

But well it's even worst now it seems to make the sensu framework to crash. 

Does anyone have an idea or know how to fix that? 

Thanks,
Sonny

**Comment by jhrv** [comment]
Hi Sonny. This has not been tested on my part at all (and should probably have removed the options for it as it's not really implemented yet :)), however having support for SSL makes good sense. 
What is the error you get in the logs with this code? And where have you placed the .pem file?

**Comment by PxSonny** [comment]
Okay, I finally have been able to make it work. 
The code I added was really necessary but my issue was in my certificate it didn't match the hostname I was actually using to access the influxdb instance (localhost). 

I will make a pull request, to merge the SSL feel free to merge it.
