### ISSUE TITLE
Sensu-server fails to stop

### ISSUE THREAD

**Issue by dzeleski** [jhrv/sensu-influxdb-extension#15]
Hi,

Im running on sensu 26.x and "service sensu-server" fails to stop:

```
# service sensu-server stop
Timed out waiting for sensu-server to stop                 [FAILED]
```

The following is in the logs:

```
{"timestamp":"2016-10-04T22:18:31.783678-0400","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-10-04T22:18:31.783882-0400","level":"warn","message":"stopping"}
{"timestamp":"2016-10-04T22:18:31.784020-0400","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-10-04T22:18:31.784368-0400","level":"warn","message":"resigning as leader"}
{"timestamp":"2016-10-04T22:18:31.784553-0400","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":458}}
{"timestamp":"2016-10-04T22:19:24.815601-0400","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-10-04T22:19:24.815895-0400","level":"warn","message":"stopping"}
{"timestamp":"2016-10-04T22:19:24.816006-0400","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-10-04T22:19:24.816208-0400","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":458}}
```

It appears this is due to the extention not calling run() as seen towards the bottom of this: https://github.com/sensu/sensu/issues/998 

Right now the only way to stop sensu is to kill -9 the pid. I use puppet to manage my sensu install so its currently not able to restart the service due to this issue. Let me know if you need further info or testing help!

**Comment by dzeleski** [comment]
Any input on this?

**Comment by jhrv** [comment]
Hi @dzeleski, what os are you running on?

**Comment by dzeleski** [comment]
@jhrv Red Hat Enterprise Linux Server release 7.2 (Maipo) Linux version 3.10.0-327.13.1.el7.x86_64

**Comment by jhrv** [comment]
This should be fixed now. Thanks to @jcomeaux for taking the time

**Comment by dzeleski** [comment]
@jhrv Ok cool Ill give this a test tomorrow morning. ~~Any idea on when this will be published to the forge?~~

Thanks for your help!

Edit: Mixed responses between open tickets, This is being tested today.

**Comment by dzeleski** [comment]
Can confirm that this is fixed. Thanks @jhrv and @jcomeaux

![image](https://cloud.githubusercontent.com/assets/8985449/20446129/c1b66648-ad9d-11e6-88f1-d376663fcffb.png)

**Comment by jhrv** [comment]
Great :)
Regarding the forge, assuming you mean puppet forge, there is currently no
such plans.

**Comment by dzeleski** [comment]
@jhrv Yeah im a jerk sorry, mixed two cases I have open, one that should be one the forge and yours. My apologies. Thanks for your help!

**Comment by jhrv** [comment]
Hey, no problem :) Your welcome!
