### ISSUE TITLE
High series cardinality

### ISSUE THREAD

**Issue by dzeleski** [jhrv/sensu-influxdb-extension#19]
Due to the way this extension imports data into influx it creates high series cardinality. Would it be possible to output in the influx protocol?

This gist: https://gist.github.com/nathanhruby/d8a64f0505477f68ce189ad8b2a88709 shows how it could be fixed but this is a mutator and not an extension. This would help influx perform much better as well.

Thoughts? @jhrv

**Comment by jhrv** [comment]
This can be fixed without a mutator. There is a pull request with a commit that might solve your problem here: https://github.com/ganeshk254/sensu-influxdb-extension/commit/575e76ec5c5a38b9a7b6dabff65b4dcd0ec50e3e

If not, there is other options as well. Do you have an example payload from sensu and expected line protocol?

**Comment by dzeleski** [comment]
Sorry didnt mean to say it needed to be a mutator only that that gist was a mutator, specifically its for a udp handler. 

Basically influx uses its own data format: https://docs.influxdata.com/influxdb/v1.1/write_protocols/line_protocol_tutorial/

The way graphite sends data causes influx to create a series for each system/metric which means influx needs to do a massive table scan. By keeping the series with just measurement names and tags it makes influx more efficient. Unfortunately that pull outputs the data in the same graphite format.

In short this check output: 
```
servername.metric.net.eth0.rx_packets 461295119435 1444234982
```

should be sent as:
```
net, host=servername, (objectname or measurement)=eth0, anotherTag=tagvalue rx_packets=461295119435 1444234982
```
Something roughly to that effect.

Heres some info on how the graphite plugin works: https://github.com/influxdata/influxdb/blob/master/services/graphite/README.md

Now because your module supports tags im ok with having to provide the host tag as a client tag in sensu if that makes things easier. But the goal here is to reduce the number of measurements. I think part of the problem will be making it so it works with many of the checks that are written already. Im just now messing around with the graphite input plugin to see if I can get it to work for us without an insane number of templates.

**Comment by dzeleski** [comment]
The other option is i re write all of the community plugin outputs to conform to the correct format and just directly feed that into influx with a udp handler.

**Comment by jhrv** [comment]
I think I understand what you are saying, so let me clarify. The extension can deal with data on either the Graphite format (key value timestamp\n) which it converts to line protocol, or it can be put in proxy-mode where it expects valid line protocol and only have a batching and sending function. 

If you are using sensu plugins where the hostname is part of the metric, you should either disable this by configuration to the plugin (this is usually provided) or rewrite it to avoid having InfluxDB create a new measurement for each host that outputs metrics. 
With your example I don't see any clear way to extract the data from the key and associate it for instance hostname.
Metadata for the metrics such as hostname should not be encoded in the measurement name, but instead provided as a client tag.
