### ISSUE TITLE
Release on rubygems.org

### ISSUE THREAD

**Issue by maoe** [jhrv/sensu-influxdb-extension#21]
Have you considered to publish this on rubygems.org? Now that sensu extensions are supposed to be packaged up as gems and to be installed using the `sensu-install` command. It would be great if you could release this on rubygems.org.

**Comment by jhrv** [comment]
Will be done as soon as possible. Pull requests are also welcome :)

**Comment by terjesannum** [comment]
https://rubygems.org/gems/sensu-extensions-influxdb

**Comment by maoe** [comment]
Thank you!
