### ISSUE TITLE
STRIP_METRIC 

### ISSUE THREAD

**Issue by humayunjamal** [jhrv/sensu-influxdb-extension#22]
Can  you please add the feature or option of adding strip_metric so if the output of metric is 
foo.load_avg.one 0.45 1494510002 I can add in the config of influxdb strip_metric="foo" and it should only out put this to the db 
load_avg.one  0.45 1494510002

?

**Comment by jhrv** [comment]
Hi, I think this should be done in the script that generates the output, and not at the extension level as this will usually handle alot of metrics from different sources and scripts.
