### ISSUE TITLE
Official influxDB extention

### ISSUE THREAD

**Issue by luisdavim** [jhrv/sensu-influxdb-extension#23]
Hi, there is now an official influxdb extension here: https://github.com/sensu-extensions/sensu-extensions-influxdb, would you consider joining forces and contributing there?

**Comment by luisdavim** [comment]
Hi again, this is causing some confusion, we have people reporting bugs for this extension on the repo for the `sensu-extensions/sensu-extensions-influxdb`.

@jhrv or @terjesannum can you take a look at this? Thanks.

**Comment by luisdavim** [comment]
please check here: https://github.com/sensu-extensions/sensu-extensions-influxdb/issues/4

**Comment by jhrv** [comment]
hi @luisdavim! Appreciate you asking,  but this is not something we're interested for the time being. 
This would likely break compatibility with regards to config, message format and features for ourself and the others ones currently using it.  We are happy with the current features and we are able to maintain it without any large efforts, so merging now does not add any value to us.

**Comment by luisdavim** [comment]
I understand, most of the features from this extension are available one the other one but the configuration is not compatible...
The problem is that you are publishing this as a gem and some people installing that think they are installing the official extension from sensu-extensions and that causes some confusion.

The idea was that we could port any missing functionality to the sensu-extensions extension.

**Comment by majormoses** [comment]
@jhrv I am a maintainer for `sensu-plugins` and `sensu-extensions` orgs, first off I completely understand and support your right to keep your namespace as you see  fit as I am a big proponent of open source. I do think that this is currently an undesired scenario as @luisdavim pointed out this is leading to a poor user experience as users think they are installing one thing and instead installing something else. If we could make the configuration compatible would you be willing to have us (we would invite you)  maintain it in the official sensu-extensions org and give us access to that namespace on rubygems? If not we are going to have to rename ours to something like `sensu-extensions-influxdb-official` or something to that effect to help users see that there is a difference but I would honestly prefer to avoid this as this still leads to a poor user experience especially for new users to sensu and ruby. 

I would not agree with this statement:
> so merging now does not add any value to us.

Having an open source community with a central location comes with many benefits such as helping new upgrading ruby versions, new features, bug fixes, confidence that there will be long term support, etc but again I respect your right to do as you see fit.

The other option is to bring what you have over into the org. @eheydrick @mbbroberg do you have any other thoughts on what we can do to bring a better user experiences?

**Comment by majormoses** [comment]
@jhrv would you at least be willing to accept a PR that has a post install message warning users that they are not installing an officially supported gem by sensu community?

**Comment by jhrv** [comment]
hi Ben, sorry for the delayed response. Been on holiday 🏖  
I don't think that would cause any less confusion for our users to add a warning message like you suggest. I think it's better that you simply rename your gem.

**Comment by majormoses** [comment]
@jhrv sorry I was away for a few days for some family emergencies. Sounds like that is the only path forward atm. In the future can I ask that anything new you create you avoid the namespace `sensu-(plugins|extensions).+` if you do not want to share your goodies with the community?

**Comment by shajithravi** [comment]
It took me a whole day to arrive at this thread. I would appreciate if both parties work out a solution. It will greatly help new users like myself not waste time debugging and running around the internet :)

@jhrv @majormoses @luisdavim

**Comment by majormoses** [comment]
@shajithravi I have made several attempts to try to reconcile the two projects but I can't force the author to give up their namespace and they were not interesting in merging functionality/projects. The author has the right to name their project as they see fit. We have renamed ours to be `sensu-extensions-influxdb2` which should help but will probably continue to be an issue for users.

**Comment by majormoses** [comment]
I would like to again at least propose https://github.com/jhrv/sensu-influxdb-extension/issues/23#issuecomment-321109403
